# =========================
# SERVER CONFIG
# =========================
server.port=4040

# =========================
# SSL / HTTPS CONFIG
# =========================
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=chatsphere

# =========================
# DATABASE
# =========================
spring.data.mongodb.uri=mongodb://localhost:27017/chatsphere

# =========================
# JWT
# =========================
jwt.secret=THIS_IS_A_DEMO_SECRET_CHANGE_IT
jwt.expiration=3600000
