server:
  port: 4040
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: chatsphere

spring:
  application:
    name: chatsphere-backend

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/chatsphere

  security:
    user:
      name: disabled
      password: disabled

logging:
  level:
    root: INFO
    com.chatsphere: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

frontend:
  url: http://localhost:5173

jwt:
  expiration-ms: 86400000 # 24 hours
